### ISSUE TITLE
[ENHANCEMENT] Keymappings

### ISSUE THREAD

**Issue by Ffrankys** [Ffrankys/wgc_ui#10]
**Vorschlag:**
FiveM Keymappings einbauen, damit der User selbst in seinen Einstellungen den Hotkey entscheiden kann.

**Comment by Cupra2Go** [comment]
Die frage ist, in welchen Einstellungen? Das Tablet selbst hat keine. Der User hat zwar bei uns welche, allerdings wie willst du auf diese zugreifen?

**Comment by Ffrankys** [comment]
Closed.

https://github.com/vCAD-Systems/vCAD_ui/commit/b157f01c9409fe018c2e701e7cd4c4a0128762bc
https://github.com/vCAD-Systems/vCAD_ui/commit/61a018d2aa07de9b20639ab2006bdd2db1c842be
